version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  main:
    jobs:
      - hello-world
